### ISSUE TITLE
Правила образования имён переменных

### ISSUE THREAD

**Issue by kuzyara** [petypen/1C_HTML_JavaScript_Test#2]
[https://its.1c.ru/db/v8std/content/2149184103/hdoc](url)
> 2. Имена следует образовывать путем удаления пробелов между словами. При этом, каждое слово в имени пишется с прописной буквы. Предлоги и местоимения из одной буквы также пишутся прописными буквами. 
> Пример:
> 
> Перем ДиалогРаботыСКаталогом; // Диалог работы с каталогом 
> Перем КоличествоПачекВКоробке; // Количество пачек в коробке
> 
> Примеры некорректных имен переменных:
> 
> масРеквизитов, соотвВидИмя, новСтр

```
Функция ТекстHTMLДокумента(Знач документHTML, сТекстДокументаHTML)
	Перем бВыполненоБезОшибок, ЗаписьDOM, ЗаписьHTML;
	
	ЗаписьDOM = Новый ЗаписьDOM();
	ЗаписьHTML = Новый ЗаписьHTML();
	ЗаписьHTML.УстановитьСтроку();
	Попытка
		ЗаписьDOM.Записать(документHTML, ЗаписьHTML);

```
_**б**ВыполненоБезОшибок_
_.Записать(**д**окументHTML, ЗаписьHTML);_
Прикольно ;)

**Comment by kuzyara** [comment]
![2018-06-13_15-35-44](https://user-images.githubusercontent.com/2604430/41339685-06458cd8-6f28-11e8-9c96-6676f5605d8d.png)
Встречается и не такое...

**Comment by petypen** [comment]
Добрый день, сошлюсь на наш [внутренний стандарт разработки](https://github.com/infosoft-v/1c-styleguide), которому мы в команде следуем.

**Comment by kuzyara** [comment]
бывает же...
